org.gradle.jvmargs=-Xmx1024m "-XX:MaxMetaspaceSize=2g"
systemProp.org.gradle.internal.http.socketTimeout=120000
kotlin.daemon.jvmargs=-Xmx2G
kotlin.stdlib.default.dependency = false

# Compile against the oldest supported MPS version (see org.modelix.mps.platform of modelix.mps-build-tools)
mps.version.major=2024.1
