package org.modelix.model.mpsplugin

import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes._return_P0_E0

/*Generated by MPS */
class _Adapters {
    class _return_P0_E0_to_Runnable_adapter(private val adapted: _return_P0_E0<out Any>) : Runnable {
        override fun run() {
            adapted.invoke()
        }
    }
}
