package org.modelix.model.mpsplugin

import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes._return_P0_E0

/*Generated by MPS */
class Adapters {
    class ReturnP0E0toRunnableAdapter(private val adapted: _return_P0_E0<out Any>) : Runnable {
        override fun run() {
            adapted.invoke()
        }
    }
}
