package org.modelix.model.mpsplugin

import com.intellij.notification.Notification
import com.intellij.notification.NotificationType
import com.intellij.notification.Notifications
import jetbrains.mps.ide.project.ProjectHelper
import jetbrains.mps.project.MPSProject

/*Generated by MPS */
object ModelixNotifications {
    private val GROUP_ID: String = "modelix"
    fun notifyWarning(title: String?, message: String?) {
        Notifications.Bus.notify(Notification(GROUP_ID, (title)!!, (message)!!, NotificationType.WARNING))
    }

    fun notifyError(title: String?, message: String?) {
        Notifications.Bus.notify(Notification(GROUP_ID, (title)!!, (message)!!, NotificationType.ERROR))
    }

    fun notifyError(title: String?, message: String?, mpsProject: MPSProject?) {
        Notifications.Bus.notify(
            Notification(GROUP_ID, (title)!!, (message)!!, NotificationType.ERROR),
            ProjectHelper.toIdeaProject(mpsProject)
        )
    }
}
