package org.modelix.model.mpsplugin

import org.modelix.model.api.IBranch
import org.modelix.model.api.IBranchListener
import org.modelix.model.client.IIndirectBranch

/*Generated by MPS */
class NonIndirectBranch(override val branch: IBranch) : IIndirectBranch {

    public override fun addListener(listener: IBranchListener) {
        branch.addListener(listener)
    }

    public override fun removeListener(listener: IBranchListener) {
        branch.removeListener(listener)
    }
}
