package org.modelix.model.mpsplugin

import org.jetbrains.mps.openapi.model.SModel
import org.modelix.model.api.INode

/*Generated by MPS */ /**
 * This represents just a pair of associated models: one physical and one on the cloud.
 */
class PhysicalToCloudModelMapping(val physicalModel: SModel?, val cloudModel: INode?)
