package org.modelix.model.mpsplugin

import com.intellij.openapi.application.ApplicationManager
import org.jetbrains.mps.openapi.module.ModelAccess
import org.jetbrains.mps.openapi.module.SRepository

/*Generated by MPS */
object WriteAccessUtil {
    fun runWrite(repo: SRepository, body: Runnable) {
        val modelAccess: ModelAccess = repo.modelAccess
        if (modelAccess.canWrite()) {
            body.run()
        } else {
            if (modelAccess.canRead()) {
                ApplicationManager.getApplication().executeOnPooledThread(object : Runnable {
                    override fun run() {
                        modelAccess.runWriteAction(body)
                    }
                })
            } else {
                modelAccess.runWriteAction(body)
            }
        }
    }
}
