package org.modelix.model.mpsplugin.history

import jetbrains.mps.ide.ThreadUtils
import jetbrains.mps.ide.ui.tree.TextTreeNode
import org.apache.log4j.LogManager
import org.apache.log4j.Logger
import org.modelix.model.mpsplugin.CloudIcons
import org.modelix.model.mpsplugin.ModelServerConnections

/*Generated by MPS */
class CloudRootTreeNode : TextTreeNode(CloudIcons.ROOT_ICON, "Cloud") {

    companion object {
        private val LOG: Logger = LogManager.getLogger(CloudRootTreeNode::class.java)
    }

    private var myInitialized: Boolean = false
    private val repositoriesListener: ModelServerConnections.IListener = object : ModelServerConnections.IListener {
        override fun repositoriesChanged() {
            val exception = ThreadUtils.runInUIThreadAndWait {
                update()
                init()
            }
            if (exception != null) {
                LOG.error("Failed to update cloud view.", exception)
            }
        }
    }

    init {
        setAllowsChildren(true)
        init()
    }

    override fun isInitialized(): Boolean {
        return myInitialized
    }

    override fun doInit() {
        myInitialized = true
        populate()
    }

    override fun doUpdate() {
        removeAllChildren()
        myInitialized = false
    }

    protected fun populate() {
        for (repo in ModelServerConnections.instance.getModelServers()) {
            add(ModelServerTreeNode(repo))
        }
    }

    override fun onAdd() {
        super.onAdd()
        ModelServerConnections.instance.addListener(repositoriesListener)
    }

    override fun onRemove() {
        super.onRemove()
        ModelServerConnections.instance.removeListener(repositoriesListener)
    }
}
