package org.modelix.model.mpsplugin.plugin

import jetbrains.mps.plugins.actions.GeneratedActionGroup
import jetbrains.mps.workbench.action.ApplicationPlugin

/*Generated by MPS */
class CloudRootGroupActionGroup(plugin: ApplicationPlugin) : GeneratedActionGroup("CloudRootGroup", ID, plugin) {
    init {
        setIsInternal(false)
        isPopup = false
        this@CloudRootGroupActionGroup.addAction("org.modelix.model.mpsplugin.plugin.AddModelServer_Action")
    }

    companion object {
        val ID: String = "org.modelix.model.mpsplugin.plugin.CloudRootGroup_ActionGroup"
    }
}
