package org.modelix.model.mpsplugin.plugin

/*Generated by MPS */
object ModelixExportConfiguration {
    private val PREFIX: String = "modelix.export."
    val PATH: String = PREFIX + "path"
    val STARTED: String = PREFIX + "started"
    val DONE: String = PREFIX + "done"
    val BRANCH_NAME: String = PREFIX + "branchName"
    val REPOSITORY_ID: String = PREFIX + "repositoryId"
    val SERVER_URL: String = PREFIX + "serverUrl"
    val GRADLE_PLUGIN_SOCKET_PORT: String = PREFIX + "gradlePluginSocketPort"
    val MAKE: String = PREFIX + "make"
}
